### ISSUE TITLE
Fragments or null elements

### ISSUE THREAD

**Issue by martinfjant** [giraffe-fsharp/Giraffe.ViewEngine#12]
Sometimes I want a partial that returns more than one HTML element, so it returns a list. But, if I want to use that as a child node along with other elements, it's not possible because a list can only hold values of the same type.

Is it possible to make a fragment (as it's called in react), that will not render any unnecessary markup, that one could wrap a list of elements in?

Sure, I could do this by concatenating lists, but that would make the code a bit more unreadable.

```
let textField name =
     label [_for name] [ste "My label"]
     input [_type "text" _name name ]

let myForm = form [_method "post" _action "/endpoint"][
                  textField "name"
                 button [_type "submit" ][str "send"]
           ]
```

This will obviously not work, and I would rather not have to wrap textField in an unnecessary div, or concatenate.

Is it possible to make an empty tag, that will not actually produce any markup to get around this?

```
let textField name =
  fragment [] [
        label [_for name] [ste "My label"]
        input [_type "text" _name name ]
  ]
let myForm = form [_method "post" _action "/endpoint"][
                  textField "name"
                 button [_type "submit" ][str "send"]
           ]
```

**Comment by dustinmoris** [comment]
All you have to do is use `yield!` in order to output elements from an `XmlNode list` into another list:

```fsharp
    let textField name = [
        label [ _for name ] [ str "My label" ]
        input [ _type "text"; _name name ]
    ]   

    let myForm = form [
        _method "post"
        _action "/endpoint" ] [
        yield! textField "name"
        button [ _type "submit" ] [ str "send" ]
    ]
```

Hope this helps!
