### ISSUE TITLE
would netstandard2.0 support be possible for this library?

### ISSUE THREAD

**Issue by kMutagene** [giraffe-fsharp/Giraffe.ViewEngine#14]
Hi there, awesome library! I am using it in various projects.

Would it be possible to support netstandard2.0 as well? I would love to use the html DSL for generation of the file scaffold for rendering plots in [Plotly.NET](https://github.com/plotly/Plotly.NET), it would make that part of the library way easier to customize and adapt. We plan to move to .net5 eventually, but so far we are stuck on netstandard2.0 and it would be awesome if you would consider supporting it if there are no major blockers. Cheers!

**Comment by TheAngryByrd** [comment]
Looks like the thing stopping going to `netstandard2.0` is the use of [ArrayPool](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.arraypool-1?view=net-5.0)

https://github.com/giraffe-fsharp/Giraffe.ViewEngine/blob/fdba5cd627919b06c516c9e94e93662f37dc706e/src/Giraffe.ViewEngine/Engine.fs#L640

Options here are:

- this is available in `netstandard2.1` but this might not be a viable option for you
- implement using only `Array.create` in `netstandard2.0` and take the increased memory pressure, which @dustinmoris would need to approve
    - I've done similar work in [FSharp.Control.Websockets](https://github.com/TheAngryByrd/FSharp.Control.WebSockets/blob/7a0f425371a4886837c6c847618561493bc966d8/src/FSharp.Control.Websockets/FSharp.Control.Websockets.fs#L228-L233) so this change wouldn't be difficult.

**Comment by dustinmoris** [comment]
Mhh.. [reading on .NET 5 and .NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-5-and-net-standard) I think targetting `netstandard2.1` adds little extra value as the latest standard which is supported by .NET Framework is `netstandard2.0`. I'm inclined to support `netstandard2.0` with the `Array.create` workaround in a compiler switch between `netstandard2.0` and `net5.0`.

**Comment by kMutagene** [comment]
@dustinmoris Cool! I filed a PR that implements the tfw specific changes, thanks @TheAngryByrd for providing the hint there!

**Comment by dustinmoris** [comment]
Just released v1.4.0 with netstandard2.0 support now. Thanks for the help and the work!
