### ISSUE TITLE
Out of date docs - Rendering?

### ISSUE THREAD

**Issue by NatElkins** [giraffe-fsharp/Giraffe.ViewEngine#2]
Hi,

Was just playing around with the library.  In this section https://github.com/giraffe-fsharp/Giraffe.ViewEngine#rendering-xml , it appears those render functions do not exist.  Is the documentation out of date?

Thanks,

Nat

**Comment by dustinmoris** [comment]
Hi Nat,

These functions should exist, but I think the docs are not good at explaining them.

Here's an example:
https://github.com/giraffe-fsharp/Giraffe.ViewEngine/blob/master/src/Giraffe.ViewEngine/Engine.fs#L635

I tried to mention it further above in the docs, but I think it's not very clear and I might have to revisit this section:

<img width="963" alt="image" src="https://user-images.githubusercontent.com/4580714/85297288-79398f00-b49a-11ea-8d66-f7c9222868af.png">

In essence you'd call it like this:

```fsharp
RenderView.AsString.xmlNodes

// or

RenderView.AsBytes.htmlDocument
```

**Comment by dustinmoris** [comment]
Ah sorry, I just realised you probably meant this:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/4580714/85297619-e0574380-b49a-11ea-96d5-7bde02eda5d3.png">


Yes you're right, that's outdated. Will fix it later 😅

**Comment by dustinmoris** [comment]
Thanks for reporting, fixed it now!
