### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by bradder555** [giraffe-fsharp/Giraffe.ViewEngine#3]
Thanks @dustinmoris for all the work you've put in since my contribution in May. 

It's looking very slick and polished now.

It'll be nice to see a cleaner commit history (most of which can be achieved with git rebase squash etc). This will help if we're ever going through the history to work out why a decision was made.

I'm happy to volunteer as a reviewer; I think you'll get more engagement from me this way too.

Since the whole github pipeline has been configured, do you think it's worth incorporating LGTM? 
https://github.com/lgtmco/lgtm

Regards
Brad

**Comment by dustinmoris** [comment]
Thank you for your help @bradder555!!! Your suggestion of splitting this out was a really good one!

> It'll be nice to see a cleaner commit history (most of which can be achieved with git rebase squash etc). This will help if we're ever going through the history to work out why a decision was made.

Agreed. Apologies, I do most of my OSS work over weekends, which also tend to go long into the night, so I too easily lose a sense for my own commit messages and I never expected someone to actually take a close look. 😳 

I'll be a lot more mindful and try to keep the commit history clean going forward!

> I'm happy to volunteer as a reviewer; I think you'll get more engagement from me this way too.

Sounds great. I can definitely do that and appreciate your offer! Have you got a particular interest in the Giraffe.ViewEngine repo or do you mean generally across all Giraffe repos?

> Since the whole github pipeline has been configured, do you think it's worth incorporating LGTM?
https://github.com/lgtmco/lgtm

Wow that looks great! Cool well let me go through the docs and understand how it works and what needs to be done and we can set something up. You're probably already familiar with it, so if you want to provide a PR with any files that need to be included and set up for LGTM then feel free to send it across!

**Comment by bradder555** [comment]
I was thinking of the viewEngine, but it can't hurt to cover all of Giraffe.

I am constrained with time, but if a PR comes through I'll do my best to review asap.

Thanks for your positive responses to my comments :)

**Comment by dustinmoris** [comment]
I sent you an invite for Triage, then you can help with PRs and code reviews in this repo!
