### ISSUE TITLE
Feliz style addition to html templating

### ISSUE THREAD

**Issue by jkone27** [giraffe-fsharp/Giraffe.ViewEngine#5]
just a proposal/suggestion: Feliz Synthax is way more straight forward for HTML templating, 
https://github.com/Zaid-Ajaj/Feliz

instead of writing (or as an alternative, e.g. ViewEngine.FelizStyle?)
```fsharp
div [ ] [
    div [ ] [ text "hello" ]
]
```
we could write
```fsharp
Html.div [
    prop.children [
        Html.div "hello"
    ]
]
```
but maybe is very complex to implement

**Comment by TheAngryByrd** [comment]
There is a [Feliz.ViewEngine](https://github.com/dbrattli/Feliz.ViewEngine) which you can use with Giraffe today.

**Comment by jkone27** [comment]
Thanks a lot! awesome!

**Comment by jkone27** [comment]
problem is Feliz.ViewEngine returns a React element, while Giraffe wants an XmlNode...  
```
Feliz.ViewEngine.Html.h1 "test" --> ReactElement
````
vs
```
 h1 [] [ encodedText "FSharpGiraffe" ] --> XMLNode
```
OK i need to change the rendering function to use the Feliz one, sorry :) 

if anyone has trouble the answer is here: https://github.com/dbrattli/Feliz.ViewEngine/blob/master/examples/giraffe/Program.fs

 👍
