### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by dsyme** [giraffe-fsharp/Giraffe.ViewEngine#8]
@Krzysztof-Cieslak @dustinmoris @bradder555  Just to say this is great and thanks for getting this to 1.0, it's an important reusable component.

(If you ever want to rename it into `FSharp.Web.ViewEngine` or something I'd support that as I consider it pretty much canonical in the F# universe, at least server-side, though I'm not particularly asking for that)

**Comment by dustinmoris** [comment]
Thanks @dsyme!

I'd support that namespace change as well, would you suggest to move the project to another organisation as part of such a rename as well?

**Comment by dsyme** [comment]
> I'd support that namespace change as well, would you suggest to move the project to another organisation as part of such a rename as well?

Well, tradition would be "fsharp" or "fsprojects" but I'd be equally happy with it staying here, there's no reason why FSharp.* namespace components can't be designed from other projects if agreed. 

There's no formal process though we should get a few more eyes cast over this, e.g. @Krzysztof-Cieslak @NinoFloris @forki @cartermp and anyone else who might have a major opinion here.

Adding /// comments, .XML in the nuget (if not there)  and a separate doc page would be good too.

**Comment by dustinmoris** [comment]
> Adding /// comments, .XML in the nuget (if not there)...

That's good feedback. I've added XML comments for most public functions except all the "HTML" tags and attributes, as they are identically named to the actual HTML tag or attribute. Could add comments there as well if that is desired.

 > ...and a separate doc page would be good too.

Ironically I've deployed [https://giraffe.wiki](https://giraffe.wiki) today. There's a link to the ViewEngine docs as well now: [https://giraffe.wiki/view-engine](https://giraffe.wiki/view-engine)

**Comment by bradder555** [comment]
I think this is a great idea

**Comment by dsyme** [comment]
@dustinmoris just to say that is fantastic documentation you've written

**Comment by dustinmoris** [comment]
Thank you, really appreciate such feedback. It's what makes me to put in the effort in writing this much docs in the first place!

**Comment by Krzysztof-Cieslak** [comment]
Renaming it to non-Giraffe specific project name sounds and making it "standard" sounds like a good idea - currently, there's a whole bunch of really similar implementations (for example - we have one in Fornax, and @dsyme has copied it to new F#.Formatting too) so having a standalone, non-product-branded version of the project that everyone could use is something I'd definitely support. 

However, changing the name and, I'd assume, namespaces would be a breaking change for Giraffe (and Saturn) - it may not be an issue given Giraffe 5.0 is still in previews, and Saturn is pre 1.0 but it's something to consider when making decisions here.

**Comment by Krzysztof-Cieslak** [comment]
Another "issue" is that with a name like `FSharp.Web.ViewEngine` we would basically pick a favourite (by giving it somehow "official" sounding name) while alternative exists - https://github.com/dbrattli/Feliz.ViewEngine by @dbrattli.

**Comment by dsyme** [comment]
> Another "issue" is that with a name like FSharp.Web.ViewEngine we would basically pick a favourite (by giving it somehow "official" sounding name) while alternative exists - https://github.com/dbrattli/Feliz.ViewEngine by @dbrattli.

Yup.  Perhaps it's just best not to unless magic alignment came about.  These DSLs aren't necessarily canonical

**Comment by dustinmoris** [comment]
Thanks for everyone's feedback. Given that there's currently nothing to do I'll close this issue. We can revisit this idea when this question/desire comes up in the future again.
