### ISSUE TITLE
Missing HtmlElement iframe

### ISSUE THREAD

**Issue by b1collector** [giraffe-fsharp/Giraffe.ViewEngine#9]
<iframe /> appears to be missing from the available HTML elements. Is it in there and I am missing it? Is there a way to add custom elements?

**Comment by b1collector** [comment]
If this is in fact a missing elements, let me know so I can create a PR.

**Comment by dustinmoris** [comment]
Hi, you're correct the iframe is a missing element currently. I've just rectified this by pushing a new release.

If you discover more missing elements or attributes then you can create new ones like this:
https://github.com/giraffe-fsharp/Giraffe.ViewEngine/tree/v1.2.0#custom-elements-and-attributes

This allows you to immediately add missing elements to your own code whilst providing a PR to this project but you're not bound to wait for a new release if you are working on something time critical. Hope that helps!
